-- MySQL Script generated by MySQL Workbench
-- 04/22/17 17:26:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema messengerDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `messengerDB` ;

-- -----------------------------------------------------
-- Schema messengerDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `messengerDB` ;
USE `messengerDB` ;

-- -----------------------------------------------------
-- Table `messengerDB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messengerDB`.`User` ;

CREATE TABLE IF NOT EXISTS `messengerDB`.`User` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messengerDB`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messengerDB`.`Message` ;

CREATE TABLE IF NOT EXISTS `messengerDB`.`Message` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Text` VARCHAR(45) NOT NULL,
  `Date` DATETIME NOT NULL,
  `IdUser` INT NOT NULL,
  `IdConversation` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Message_Conversation1_idx` (`IdConversation` ASC),
  INDEX `fk_Message_User1_idx` (`IdUser` ASC),
  CONSTRAINT `fk_Message_Conversation1`
    FOREIGN KEY (`IdConversation`)
    REFERENCES `messengerDB`.`Conversation` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `messengerDB`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messengerDB`.`Conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messengerDB`.`Conversation` ;

CREATE TABLE IF NOT EXISTS `messengerDB`.`Conversation` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `CreatedDate` DATETIME NOT NULL,
  `IdCreator` INT NOT NULL,
  `IdLastMessage` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Conversation_User1_idx` (`IdCreator` ASC),
  INDEX `fk_Conversation_Message1_idx` (`IdLastMessage` ASC),
  CONSTRAINT `fk_Conversation_User1`
    FOREIGN KEY (`IdCreator`)
    REFERENCES `messengerDB`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conversation_Message1`
    FOREIGN KEY (`IdLastMessage`)
    REFERENCES `messengerDB`.`Message` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messengerDB`.`ConversationUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messengerDB`.`ConversationUser` ;

CREATE TABLE IF NOT EXISTS `messengerDB`.`ConversationUser` (
  `IdUser` INT NOT NULL,
  `IdConversation` INT NOT NULL,
  PRIMARY KEY (`IdUser`, `IdConversation`),
  INDEX `fk_ConversationUser_User1_idx` (`IdConversation` ASC),
  CONSTRAINT `fk_ConversationUser_Conversation`
    FOREIGN KEY (`IdConversation`)
    REFERENCES `messengerDB`.`Conversation` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConversationUser_User1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `messengerDB`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messengerDB`.`Auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messengerDB`.`Auth` ;

CREATE TABLE IF NOT EXISTS `messengerDB`.`Auth` (
  `idUser` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  PRIMARY KEY (`idUser`),
  CONSTRAINT `fk_Auth_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `messengerDB`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
